; Show errors (very important for dev)
display_errors = On
display_startup_errors = On
error_reporting = E_ALL

; Log errors (optional but useful)
log_errors = On
error_log = "C:\Windows\Temp\php_errors.log"

; Increase upload limits
upload_max_filesize = 50M
post_max_size = 50M

; Execution limits
max_execution_time = 300
max_input_time = 300
memory_limit = 512M

; Default timezone (IMPORTANT)
date.timezone = Africa/Tunis

; Enable extensions (example)
extension=mysqli
extension=pdo_mysql

; Sessions
session.save_path = "C:\Windows\Temp"
session.gc_maxlifetime = 1440

; File uploads
file_uploads = On

; Allow URL fopen (needed for some apps)
allow_url_fopen = On
extension_dir = "C:\Users\oussema.bh\AppData\Local\Programs\PHP\8.5.4\nts\x64\ext"