
display_errors = On
display_startup_errors = On
error_reporting = E_ALL


log_errors = On
error_log = "C:\Windows\Temp\php_errors.log"


upload_max_filesize = 50M
post_max_size = 50M


max_execution_time = 300
max_input_time = 300
memory_limit = 512M


date.timezone = Africa/Tunis


extension=mysqli
extension=pdo_mysql


session.save_path = "C:\Windows\Temp"
session.gc_maxlifetime = 1440


file_uploads = On


allow_url_fopen = On
extension_dir = "C:\Users\oussema.bh\AppData\Local\Programs\PHP\8.5.4\nts\x64\ext"
